repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

      # - id: check-yaml
      # could not determine a constructor for the tag
      # 'tag:yaml.org,2002:python/name:material.extensions.emoji.twemoji'
      # in "mkdocs.yaml"

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
