site_author: Anshul Raj Verma
site_description: Anshul's personal website for showcasing his learnings, blogs and more.
site_name: ARV
site_url: https://arv-anshul.github.io

theme:
  language: en
  name: material
  font:
    text: Rubik
  icon:
    repo: material/book
    logo: fontawesome/solid/om
  logo: null
  favicon: data/assets/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    scheme: slate
    primary: black

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
      archive_date_format: MMMM, yyyy
      archive_url_date_format: yyyy/MM
      categories_url_format: "c/{slug}"
      post_url_format: "{slug}"
      pagination_per_page: 5
      pagination_format: $link_first $link_previous ~2~ $link_next $link_last
  - search: null
  - macros:
      include_yaml:
        - about: docs/data/render_yaml/about.yaml
        - friends: docs/data/render_yaml/friends.yaml
        - learn_stuff: docs/data/render_yaml/learn_stuff.yaml
        - other_projects: docs/data/render_yaml/other_projects.yaml
        - projects_index: docs/data/render_yaml/projects_index.yaml
        - recommendations: docs/data/render_yaml/recommendations.yaml
  - redirects:
      redirect_maps:
        campusx-dsmp.md: https://arv-anshul.github.io/campusx
        campusx-dsmp/resources.md: https://arv-anshul.github.io/campusx/dsmp2
        gh.md: https://github.com/arv-anshul
        github.md: https://github.com/arv-anshul
        linkedin.md: https://linkedin.com/in/arv-anshul
        notebooks.md: https://github.com/arv-anshul/notebooks
        project/notebooks.md: https://github.com/arv-anshul/notebooks
        project/dotfiles.md: https://github.com/arv-anshul/dotfiles
        project/yt-watch-history-v2/index.md: project/yt-watch-history/index.md
        projects/index.md: project/index.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_PROPERTY
    feedback:
      title: Did you like it?
      ratings:
        - icon: fontawesome/solid/face-grin-wink
          name: Yep!
          data: 1
          note: Thanks for your feedback!
        - icon: fontawesome/solid/face-frown
          name: Nope!
          data: 0
          note: Thanks for your feedback!
  social:
    - icon: material/email
      link: mailto:arv.anshul.1864@gmail.com
      name: E-Mail
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/_batookm
      name: Connect on Instagram
    - icon: simple/pypi
      link: https://pypi.org/user/arv-anshul/
      name: See My Python Projects PyPi
    - icon: simple/huggingface
      link: https://hf.co/arv-anshul
      name: HuggingFace Profile
    - icon: fontawesome/brands/github
      link: https://github.com/arv-anshul
      name: See my GitHub Profile
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arv-anshul
      name: Connect on LinkedIn
    - icon: material/account-box
      link: https://github.com/arv-anshul/arv-anshul/raw/main/resume_arv-anshul.pdf
      name: Resume as PDF

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/arv-anshul">Anshul Raj Verma</a>

extra_css:
  - stylesheets/custom.css
  - stylesheets/extra.css
  - stylesheets/simpleicons.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

nav:
  - Home:
      - index.md
      - friends.md
      - anime.md
      - movies.md
      - music.md
  - Projects:
      - project/index.md
      - project/others.md
      - project/notebooks.md
      - project/canvas-ai.md
      - Youtube Watch History:
          - project/yt-watch-history/index.md
          - project/yt-watch-history/ctt.md
          - project/yt-watch-history/channel_reco.md
          - project/yt-watch-history/v2-architecture.md
          - project/yt-watch-history/v2-channel_reco.md
      - project/spotify-analysis.md
      - project/campusx.md
      - project/credit-risk-modeling.md
      - project/dotfiles.md
  - References:
      - ref/index.md
      - ref/learn-stuff.md
      - ref/resume-tips.md
      - Python:
          - ref/python/rye.md
      - Bash:
          - ref/bash/tips.md
          - blog/posts/starship.md
          - ref/bash/useful-commands.md
      - Statistics:
          - blog/posts/basics-of-statistics.md
      - Deep Learning:
          - ref/deep-learning/index.md
  - Blog:
      - blog/index.md
  - About: about/index.md
