"""
This script generates the css at `docs/stylesheets/simpleicons.css`.

It generates color for every tech which is specified in `data/simpleicons.json` file
using `simpleicons` library.

Go to simple-icons website: https://simpleicons.org
Check `simpleicons` library: https://github.com/sachinraja/simple-icons-py
"""

import json
import logging
from pathlib import Path

from simpleicons import icons
from simpleicons.icon import Icon

SIMPLEICONS_CSS_PATH = Path("docs/stylesheets/simpleicons.css")
SIMPLEICONS_JSON_PATH = Path("data/simpleicons.json")

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:    -  %(message)s",
)


def generate_tech_css(tech_data: dict[str, str]) -> str:
    """Generates CSS for each tech."""
    css_rules = [
        "/*\n😎 Generated by 'docs_src/generate_simpleicons_css.py'\n*/\n",
    ]
    for tech, color in tech_data.items():
        if tech.endswith("-hover"):
            css_rules.append(f".{tech}:hover {{ color: #{color}; }}")
        else:
            css_rules.append(f".{tech} {{ color: #{color}; }}")
    return "\n".join(css_rules) + "\n"


def generate_simpleicons_css() -> None:
    simpleicons_data: set[str] = set(json.loads(SIMPLEICONS_JSON_PATH.read_bytes()))

    tech_colors: dict[str, str] = {}
    for tech in sorted(simpleicons_data):
        try:
            icon: Icon = getattr(icons, f"si_{tech}")
        except AttributeError:
            logging.warning(f"{tech!r} not in 'simpleicons.icon' module.")
            tech_colors[tech] = "FFFFFF"
            tech_colors[f"{tech}-hover"] = "FFFFFF"
            continue
        else:
            tech_colors[tech] = icon.hex
            tech_colors[f"{tech}-hover"] = icon.hex

    simpleicons_css = generate_tech_css(tech_colors)
    SIMPLEICONS_CSS_PATH.write_text(simpleicons_css)


if __name__ == "__main__":
    generate_simpleicons_css()
