"""
This script generates the css at `docs/stylesheets/simpleicons.css`.

It generates color for every tech which is specified in `data/simpleicons.json` file
using `simpleicons` library.

Go to simple-icons website: https://simpleicons.org
Check `simpleicons` library: https://github.com/sachinraja/simple-icons-py
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from simpleicons import icons

SIMPLEICONS_CSS_PATH = Path("docs/stylesheets/simpleicons.css")
SIMPLEICONS_JSON_PATH = Path("data/simpleicons.json")

UNAVAILABLE_ICONS = {
    "arc": "FCBFBD",
    "json": "var(--md-typeset-color)",
    "materialformkdocs": "526CFE",
    "polars": "CD792C",
    "pydantic": "E92063",
    "raycast": "FF6363",
    "ruff": "D7FF64",
    "rust": "var(--md-typeset-color)",
    "rye": "90c820",
    "zedindustries": "084CCF",
}

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:    -  %(message)s",
)


def generate_tech_css(tech_data: dict[str, str]) -> str:
    """Generates CSS for each tech."""
    css_rules = [
        "/*\n😎 Generated by 'docs_src/generate_simpleicons_css.py'\n*/\n",
    ]
    for tech, color in tech_data.items():
        css_rules.append(f".{tech} {{ color: {color}; }}")
        css_rules.append(f".{tech}-hover:hover {{ color: {color}; }}")
    return "\n".join(css_rules) + "\n"


def generate_simpleicons_css() -> dict[str, str]:
    simpleicons_data: set[str] = set(json.loads(SIMPLEICONS_JSON_PATH.read_bytes()))

    tech_colors: dict[str, str] = {}
    for tech in sorted(simpleicons_data):
        try:
            icon_hex = UNAVAILABLE_ICONS.get(tech) or getattr(icons, f"si_{tech}").hex
        except AttributeError:
            logging.warning(f"{tech!r} not in 'simpleicons.icon' module.")
            icon_hex = "FFFFFF"
        tech_colors[tech] = icon_hex if icon_hex.startswith("v") else f"#{icon_hex}"
    return tech_colors


if __name__ == "__main__":
    tech_colors = generate_simpleicons_css()
    simpleicons_css = generate_tech_css(tech_colors)
    SIMPLEICONS_CSS_PATH.write_text(simpleicons_css)
