authors:
  arv-anshul:
    name: Anshul Raj Verma
    description: Creator
    avatar: https://github.com/arv-anshul.png
    url: https://github.com/arv-anshul
  campusx:
    name: CampusX
    description: Mentor • Teacher
    avatar: https://github.com/campusx-official.png
    url: https://youtube.com/@campusx-official
  chatgpt:
    name: ChatGPT
    description: Bot
    avatar: https://github.com/openai.png
    url: https://chat.openai.com
