name: Build Docs
on:
  push:
    paths:
      - docs/**
      - mkdocs.yaml
      - .github/workflows/**
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Setup cache for CI
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Finally build docs and publish
        env:
          GOOGLE_ANALYTICS_PROPERTY: ${{ secrets.GOOGLE_ANALYTICS_PROPERTY }}
        run: uv run --no-dev --locked mkdocs gh-deploy --force
